definitions:
  model.Courier:
    properties:
      courier_id:
        type: integer
      courier_type:
        type: string
      regions:
        items:
          type: integer
        type: array
      working_hours:
        items:
          $ref: '#/definitions/model.TimeInterval'
        type: array
    type: object
  model.Error:
    type: object
  model.TimeInterval:
    type: object
info:
  contact: {}
  title: Yandex Lavka
  version: "1.0"
paths:
  /couriers/{courier_id}:
    get:
      consumes:
      - application/json
      operationId: courier_get
      parameters:
      - description: Courier identifier
        in: path
        name: courier_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            items:
              $ref: '#/definitions/model.Courier'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.Error'
      summary: Создание пользователя
      tags:
      - User
swagger: "2.0"
